# Test the example Notebooks of IPS

name: pytest

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '14 3 * * 1'  # at 03:14 on Monday.

jobs:
  examples:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          pipx install poetry
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install package
        run: |
          poetry install --all-extras
      - name: Setup git user
        run: |
          git config --global user.name "John Doe"
          git config --global user.email johndoe@example.com
          git config --global init.defaultBranch "main"
      - name: clone repository
        run: |
          git clone https://github.com/PythonFZ/IPS-Examples 
          cd IPS-Examples
          git fetch origin
      - name: intro
        run: |
          cd IPS-Examples
          git checkout intro
          poetry run dvc pull
          poetry run jupyter nbconvert --to notebook --execute main.ipynb
          poetry run dvc repro -f
          rm -rf nodes/
          git reset --hard




